### ISSUE TITLE
Not able to read signed character

### ISSUE THREAD

**Issue by rkpadhi2050** [rbheemana/Cobol-to-Hive#11]
in Copybook below are there.

FIELDNAME  PIC S9(011)V99
                   SIGN TRAILING SEPARATE.
After deserialisation I am getting below column converted in HIVE.
FIELDNAME(13,3) and the value is 20.398 ... Instead 203.98  as V99 is there in the end.

Can yu please let me what could be the issue?

**Comment by rkpadhi2050** [comment]
And i am not able to see SIGNED character after deserialisation

**Comment by rbheemana** [comment]
Could you please explain me difference between fields defined as 
1) FIELDNAME PIC S9(011)V99.
and 
2) FIELDNAME PIC S9(011)V99 SIGN TRAILING SEPARATE.

Current code doesnot have special code for "SIGN TRAILING SEPARATE". Try defining the field with option 1 and see. Also please use latest jar and do describe table, this will show the mainframe copybook field details, offset and length in comments of the column.

**Comment by rbheemana** [comment]
I hope issue is resolved by using serde3. closing the issue.
