### ISSUE TITLE
Column names remains static

### ISSUE THREAD

**Issue by rbheemana** [rbheemana/Cobol-to-Hive#12]
Once table is created, drop and create is not updating column names with new copy book details.

Details:
when creating a new table and does a describe on it.. its showing the table layout of the previous table.. set cobol.hive.mapping, this is also showing old layout(created using previous cobol copy book).

when creating external table A that points to copybook A, that works fine. But when creating another external table B pointing to another copybook B in a different location, the original table A structure has been replace with table B. Now Table A and B is having the same structure.

When i drop and recreate the table in hive cli, it is showing new ddl. but in hue its still showing the old ddl of the table.

**Comment by rbheemana** [comment]
Code has been updated. Try new jar.

**Comment by sandeep-tandon** [comment]
Hi Ram, 

Where can i get the jar which is updated with this issue.

Regards,
Sandeep
