### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by jaz0020** [rbheemana/Cobol-to-Hive#14]
Hi ,
I did try your code to run on hive. But i get no data back when i query the cobol2hive table . i have attached the file i have tried and also the code.
[input.txt](https://github.com/rbheemana/Cobol-to-Hive/files/443382/input.txt)
[bc70copy.txt](https://github.com/rbheemana/Cobol-to-Hive/files/443384/bc70copy.txt)
Kindly help with this request.

**Comment by datawarlock** [comment]
Try this version of the copybook.  I cleaned it up and simplified it a bit.

[bc70copy_update.txt](https://github.com/rbheemana/Cobol-to-Hive/files/452797/bc70copy_update.txt)

**Comment by rbheemana** [comment]
@jaz0020 Please close the issue if it is resolved.
