### ISSUE TITLE
issues while using cobol serde

### ISSUE THREAD

**Issue by kamelia78** [rbheemana/Cobol-to-Hive#16]
Hello!

Thank you for this great work.
I'm testing the conversion of an EBCDIC File to Hive Table and have some issues:

When using in Hive:
ROW FORMAT SERDE 'com.savy3.hadoop.hive.serde3.cobol.CobolSerDe'
I have the following error:
Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. org.apache.hadoop.hive.ql.metadata.HiveException: at least one column must be specified for the table

HOWEVER,
when using:
ROW FORMAT SERDE 'com.savy3.hadoop.hive.serde2.cobol.CobolSerDe'
It works, but the format PIC S9(8)V9(3) USAGE COMP-3. is not correct for decimals:
8 instead of 8.1
9.16 instead of 9.216

Could you please help ?
Thanks!

Below the complete DLL

`ADD JAR hdfs://cluster/user/username/cobolserde.jar;
CREATE EXTERNAL TABLE IF NOT EXISTS new_table
ROW FORMAT SERDE 'com.savy3.hadoop.hive.serde3.cobol.CobolSerDe'
STORED AS
INPUTFORMAT 'org.apache.hadoop.mapred.FixedLengthInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
LOCATION '/TMP/DATA'
TBLPROPERTIES ('cobol.layout.url'= 'hdfs://cluster/user/username/my_layouts/layout','fb.length'='120')`

**Comment by datawarlock** [comment]
Could you please post the copybook you are using for serde3.  That error is usually related to a structural issue with the layout.

Serde3 should be used over Serde2.

**Comment by kamelia78** [comment]
Hello!

Yes sure:
`20 DOC2-V-ID           PIC X(17).
         20 DOC2-N-DATA         PIC S9(04) COMP-3.
         20 DOC2-VAL-DATA         PIC X(100).`

**Comment by datawarlock** [comment]
Use this:

01 DOC2.
  20 DOC2-V-ID PIC X(17). 
  20 DOC2-N-DATA PIC S9(04) COMP-3. 
  20 DOC2-VAL-DATA PIC X(100).

**Comment by rbheemana** [comment]
Use this: Since there is a  [issue](https://github.com/rbheemana/Cobol-to-Hive/issues/18) with even numbered COMP-3 variables. Hope this resolves the issue.
01 DOC2.
20 DOC2-V-ID PIC X(17). 
20 DOC2-N-DATA PIC S9(5) COMP-3. 
20 DOC2-VAL-DATA PIC X(100).

**Comment by karthiktsb** [comment]
Hi,

I tried using the CobolSerde.jar which was downloaded from here and when I try to add the jar file in Hive it gives me the following error -

Illegal character in scheme name at index 0: 'hdfs://hdpdev/user/ktk/hive/jars/CobolSerde.jar'
Query returned non-zero code: 1, cause: java.net.URISyntaxException: Illegal character in scheme name at index 0: 'hdfs://hdpdev/user/kthiruk/hive/jars/CobolSerde.jar'
..

Could someone please help with resolving this error.
