### ISSUE TITLE
Issue while using the cobol2hive serde, comp & com 3 not getting converted

### ISSUE THREAD

**Issue by Aniket02** [rbheemana/Cobol-to-Hive#17]
Hi Ram,

We need your guidance to solve the below issue
Description: - 
We have received a binary file containing COMP and COMP 3 fixed length file.
The table is getting created using the cobol2hive serde with all the required columns based on the copy book with all the data type matching.

Below are few of the issues while transforming the data: - 
1. While doing select \* from abc; we are getting below error
Error: java.io.IOException: java.io.IOException: Partial record(length = 48) found at the end of split. (state=,code=0)
2. column with comp field are not getting converted properly.
For example value for COMP column which is '10001' in actual mainframe data file, we are getting 538978065 in the table.
3. The Mainframe file imported seems to be correct but the output table is not getting populated correctly for COMP and COMP 3

Sincerely,
Aniket

**Comment by datawarlock** [comment]
Aniket - 

For item 1 that error comes up with the file was not transferred correctly.  Make sure that you transfer in binary mode and if it is a fixed block file to give the LRECL on transfer.

Make sure that is addressed first.  If the other issues still exist after this please reply with the copybook and the errors.

Thanks!
Patrick

**Comment by Aniket02** [comment]
Thank you, Patrick! We are getting the binary files from a FTP server into Hadoop. The binary files have been loaded on the FTP server from Mainframe. From what I understand, "LRECL on transfer", and "BINARY
QUOTE SITE RDW"
needs to be part of the FTP script used to get the files from mainframe into FTP; nothing needs to be defined from FTP to Hadoop?

Sincerely,
Aniket

**Comment by datawarlock** [comment]
Is it an FB or VB file?  When transferring a FB file you need Binary and Lrecl. For VB you need binary, RDW , AND blocksize.

**Comment by Aniket02** [comment]
The file I am currently testing is FB, but will be working with VB files as well. Thanks!

**Comment by Aniket02** [comment]
Hi Patrick,
I have one issue while using the Serde, can you please shed some light on it?

 Below I have mentioned how Serde is converting my S9(2) comp-3 variable, I can see it is picking the length as 1 instead of 2 . It is calculating perfectly for other copybook variables (including other comp-3).

Column name | Data type | Copybook description                                  | start position |  Length
 q_day_led       |  tinyint      | 10 Q-DAY-LED PIC S9(2)V USAGE COMP-3 | 147                 | 1

Thanks.

**Comment by datawarlock** [comment]
Could you post your full copybook for me to take a look at?

**Comment by datawarlock** [comment]
I did notice that your value in the output it says this was in the copybook:
PIC S9(2)V
Do you expect this value to be a decimal?  Also the Serde does not like the short hand syntax for fields.  So things like this:
PIC X should be updated to to PIC X(1).

This could be the issue with the short handed V after the PIC S9(2)V
I believe it should be PIC S9(2)V9(1)

**Comment by Aniket02** [comment]
Hi Patrick,
Thanks for the advice, Yes I have tried this option already but the result was same. I am attaching a similar copybook and Serde converted table metadata. Just curious why the Serde is calculating length of s9(2) comp-3 as 1. Please if you can have a look, and advise, it would be great! Thanks. 
[Copybook1.txt](https://github.com/rbheemana/Cobol-to-Hive/files/542865/Copybook1.txt)
[Data created by Serde.docx](https://github.com/rbheemana/Cobol-to-Hive/files/542866/Data.created.by.Serde.docx)

**Comment by datawarlock** [comment]
Hi Aniket

Something else that I just realized.  You have the field defined as s9(2) comp-3.  The number of positions for the serde has to be odd.  Change your field definition to s9(3) comp-3.  The reason for this is how packed values work.  The number of bytes a PIC S9(m) takes is (m+1)/2.  So the number of bytes used for 9(2) and a 9(3) are the same.  The last nibble of the byte will contain the "sign" of the value.  Mainframes can implicitly deal with this but you have to explicitly change the value for the serde to handle it.

So in general the rule should be if you have a comp-3 you need to have an odd number for length.

I have recently had to deal with this issue myself.
Let me know if that works.
Thanks!

**Comment by Aniket02** [comment]
Hi Patrick,

Thanks a lot Patrick for your input, yes, that works, and the file loads perfectly!

Sincerely,
Aniket

**Comment by rbheemana** [comment]
Hi Patrick,
Appreciate that you are helping others. Good to have people like you.
 So below issue sounds like a bug in the code. Would you be able to fix that in number field.Java and test it. If yes, that would be great. I am currently short of mainframe input to do it myself.
Thanks,
Ram

**Comment by datawarlock** [comment]
Hey Ram,

I think I can handle that.  It will take me a little bit.  It is a busy week for me but I should be able to get to it some time this week or maybe early next week.

Thanks!
Patrick

**Comment by rbheemana** [comment]
thanks sent you collaborator request, accept it and you would be able to commit changes to repository

**Comment by ameet123** [comment]
Hi Guys,

We are having a similar problem, 
Here are the symptoms,
original copybook had `S99` which was showing a value ==> null
we changed it to S9(2), still showing the same value     ==> null
we changed it to,   S9(3) COMP-3                                  ==> 15012
real value is 1

I'd appreciate if you can offer any insights or ideas on how to solve this.

thanks much,

ameet
