### ISSUE TITLE
COMP-3 Fields with even number of values is not calculating length properly.

### ISSUE THREAD

**Issue by rbheemana** [rbheemana/Cobol-to-Hive#18]
The number of bytes a PIC S9(m) COMP-3 takes is (m+1)/2. So the number of bytes used for 9(2) and a 9(3) are the same. The last nibble of the byte will contain the "sign" of the value. Mainframes can implicitly deal with this but you have to explicitly change the value for the serde to handle it.

SERDE should create length as 2 for S9(2) COMP-3. Currently it is creating a length of 1.

**Comment by datawarlock** [comment]
Hey Ram - We (myself and a team member) have made some changes to the serde.  I have submitted a pull request for your review.

**Comment by tejasbharambe** [comment]
Hey Patrick - what are the modifications that you have done to serde? Any extra functionality is added?

**Comment by rbheemana** [comment]
@datawarlock @josephlim75 @ankravch @tejasbharambe  I have updated the code to resolve this issue in the branch Issue#18. I have also added test cases. Would you be able to download compile and test the code if it works as expected. If u could confirm the changes looks good, I can merge the Issue#18 branch to Main branch. Thanks in advance for all the help.

**Comment by rbheemana** [comment]
Code is merged closing the issue.
