### ISSUE TITLE
issues while using cobol serde

### ISSUE THREAD

**Issue by zizou221190** [rbheemana/Cobol-to-Hive#19]
hello 
I have error when I use ROW FORMAT SERDE 'com.savy3.hadoop.hive.serde3.cobol.CobolSerDe'
Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. org.apache.hadoop.hive.ql.metadata.HiveException: at least one column must be specified for the table

I followed this issues but not success #16 
I used this copybook 

01 DOC2.
 20 DOC2-V-ID PIC X(17). 
 20 DOC2-N-DATA PIC S9(5) COMP-3. 
 20 DOC2-VAL-DATA PIC X(100).

could you help me please ?
thanks

**Comment by rbheemana** [comment]
Are you sure you are pointing to correct copybook. Also make sure there is a space after '.'  Please share complete create DDL.

**Comment by zizou221190** [comment]
hello 
yes sure :
ADD JAR hdfs://cluster/user/username/cobolserde.jar;
CREATE EXTERNAL TABLE IF NOT EXISTS cobol_test10
ROW FORMAT SERDE 'com.savy3.hadoop.hive.serde3.cobol.CobolSerDe'
STORED AS
INPUTFORMAT 'org.apache.hadoop.mapred.FixedLengthInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
LOCATION '/TMP/DATA'
TBLPROPERTIES ('cobol.layout.url'= 'hdfs:///cluster/user/username/my_layout/layout','fb.length'='121') 

thanks

**Comment by rbheemana** [comment]
@zizou221190 sorry for delay in response, are you able to get past the error. Please let us know if you still need assistance.

**Comment by rbheemana** [comment]
I have updated test case TestCobolHiveTableCreation to have table create with this layout. It worked perfectly fine. Hence closing the issue.
https://github.com/rbheemana/Cobol-to-Hive/tree/Issue%2351-Field-with-format-S9(11)V99-displays-null-value-in-hive
