### ISSUE TITLE
skipping few fields 

### ISSUE THREAD

**Issue by catchcharan** [rbheemana/Cobol-to-Hive#24]
My copybook is relatively very huge. FB length of 1806. 

Your steps worked great and I could able to create table and view data. Only issue I observed is it skipped several fields of copybook and created the rest as table columns from there. 

Could you please throw some light on why several lines of copybook might got skipped?

Thanks,
Charan

**Comment by rbheemana** [comment]
Please posted which fields missed and its corresponding copybook..

**Comment by catchcharan** [comment]
Please ignore my post. It skipped because copybook used PICTURE X instead of PIC X.After little debugging able to get there. Now I can see all fields.

**Comment by rbheemana** [comment]
Opened new issue for this https://github.com/rbheemana/Cobol-to-Hive/issues/30
