### ISSUE TITLE
Password encryption

### ISSUE THREAD

**Issue by atul96** [rbheemana/Cobol-to-Hive#25]
@rbheemana everything written in this blog is working fine for me. however is there a way to 
hide or make a password alias in the following command.
hadoop jar Cobolserde.jar {hostid:port} {username} {password}{mf_file} {location}. I am using this command in shell script.(hadoop jar CobolSerde.jar mf_host:21 atul96 main123 'acx.fds.fd(0)' /atul/mf     So now how do I hide my password 'main123'. I want to run this in production environment.

**Comment by rbheemana** [comment]
u can implement jceks file or file path for password similar to SQOOP by altering the code.

**Comment by rbheemana** [comment]
Closing this defect as it can be handled outside this project.
