### ISSUE TITLE
Signed Packed decimals

### ISSUE THREAD

**Issue by catchcharan** [rbheemana/Cobol-to-Hive#26]
COMP-3 PIC S9(08)V99.

Sorry, If I missed this in the documentation. How should I be defining signed packed values in copybook?

**Comment by datawarlock** [comment]
PIC S9(9)V9(1) COMP-3.

Note the 8 was changed to a 9 due to a current issue that I will be correcting in the near future.

**Comment by rbheemana** [comment]
duplicate issue#18
