### ISSUE TITLE
"LAYOUT_GEN" error

### ISSUE THREAD

**Issue by boltunoff** [rbheemana/Cobol-to-Hive#27]
Hi Ram,
I am having this error while creating Hive table:
"Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. LAYOUT_GEN"

Will you please comment, help.

**Comment by rbheemana** [comment]
Please share the copybook layout.

**Comment by rbheemana** [comment]
closing this issue as no further details are provided.
