### ISSUE TITLE
Not converting decimal location correctly comp 3

### ISSUE THREAD

**Issue by tejasbharambe** [rbheemana/Cobol-to-Hive#28]
It is not able to convert the comp 3 decimal location. As a result it is only showing one row of data in table. 
Where as we have 100 rows of data. 
Any idea where I am going wrong? 
Fir the S9(15)V9(2) COMP-3 Field!

**Comment by datawarlock** [comment]
Can you please post the full copy book you are using?  Also - is it an FB or VB file?

**Comment by tejasbharambe** [comment]
thank you for your replying
[ASCIIofebcdic_test_file.txt](https://github.com/rbheemana/Cobol-to-Hive/files/781653/ASCIIofebcdic_test_file.txt)

the copybook is below . it is nt converting the last column and it is only showning 1 row
[test_ebcdic_159.txt](https://github.com/rbheemana/Cobol-to-Hive/files/781658/test_ebcdic_159.txt)

**Comment by tejasbharambe** [comment]
I have replied on github. Please help It is of fixed length. FB

**Comment by datawarlock** [comment]
Would you be able to post the raw ebcdic data?

**Comment by tejasbharambe** [comment]
@datawarlock.  I have emailed you the raw ebcdic data

**Comment by tejasbharambe** [comment]
Raw ebcdic data is attached here :
[ebcdic_test_file.txt](https://github.com/rbheemana/Cobol-to-Hive/files/782596/ebcdic_test_file.txt)

**Comment by tejasbharambe** [comment]
here is the screenshot after running the query;
   
![screenshot](https://cloud.githubusercontent.com/assets/13090104/23057688/492b871e-f517-11e6-95f9-c5f1cdac34c0.png)

It is not converting the decimal properly and it is only displaying one row.

**Comment by ankravch** [comment]
It looks like CobolSerde doesn't correctly deduce a variable length for cobol copybook ending with COMP-3 variable.

After appending PIC X(3). variable to copybook and its binary value (b'\xc7\xc7\xc7' for example) to binary ebcdic data, SPrice seems to get correct values. 
```python
hive> select * from c2h_mod limit 20;
OK
 Grover                          23032014  Olympia                                              Ohio                                                17012016 17943 14940.82 GGG
 Warren                          05082015  Annapolis                                            New York                                            22092014 18140 38748.28 GGG
 Millard                         08082013  Indianapolis                                         California                                          21062015 14879 29366.57 GGG
 William                         20092015  Albany                                               Utah                                                15112015 20231 60097.81 GGG
 Millard                         02052013  Topeka                                               California                                          06022014 22534 17285.28 GGG
 Grover                          19032013  Annapolis                                            Oregon                                              23112014 7674 32356.41 GGG
 James                           18042014  Sacramento                                           Idaho                                               25072015 16532 53500.82 GGG
 Bill                            03122015  Denver                                               Maryland                                            22042014 11734 50482.58 GGG
 Woodrow                         31052015  Pierre                                               Florida                                             02122014 10618 31610.08 GGG
 Woodrow                         10042014  Madison                                              Tennessee                                           03082014 22276 6665.08 GGG
 William                         25042013  Lincoln                                              Arizona                                             10022014 18289 62958.86 GGG
 Thomas                          05112013  Dover                                                Iowa                                                15022015 8532 27927.43 GGG
 Chester                         23102015  Topeka                                               Indiana                                             29082014 16389 17528.41 GGG
 Rutherford                      09072015  Montpelier                                           Hawaii                                              08072014 18347 13844.57 GGG
 Lyndon                          25032015  Madison                                              Massachusetts                                       19032014 19076 59804.13 GGG
 Bill                            26102015  Austin                                               Arizona                                             18072015 18174 21841.38 GGG
 Dwight                          08072014  Boston                                               Utah                                                08072015 23269 52407.53 GGG
 Jimmy                           11072013  Columbia                                             Kentucky                                            05102015 8563 23780.61 GGG
 George                          19022014  Trenton                                              Kansas                                              12062015 17030 11216.41 GGG
 Herbert                         09052013  Little Rock                                          Colorado                                            05012015 17692 53954.65 GGG
20 rows selected (0.106 seconds)
hive> describe extended c2h_mod;
OK
customername varchar(30)  10 CustomerName PIC X(30)|0|30
purchasedate varchar(8)  10 PurchaseDate PIC X(8)|30|8
city varchar(50)  10 City PIC X(50)|38|50
state varchar(50)  10 State PIC X(50)|88|50
mdate varchar(8)  10 MDate PIC X(8)|138|8
mprice bigint  10 MPrice PIC S9(9) COMP-3|146|5
sprice decimal(16,2)  10 SPrice PIC S9(14)V9(2) COMP-3|151|8
eoc varchar(3)  10 EOC PIC X(3).|159|3
```

**Comment by tejasbharambe** [comment]
Thank you soo much @ankravch. 

Could you please elaborate on why that is happening?. 
Any idea where to correct that code?

**Comment by tejasbharambe** [comment]
How to append that binary value to the ebcdic data file?

**Comment by datawarlock** [comment]
Just add a filler field to the copybook.  That should do it.

Patrick J. Watts
Senior Principal Consultant - Cloud Engineering
m: 630.873.9180
pwatts@clarity-us.com
Clarity Solution Group | www.clarity-us.com

**Comment by tejasbharambe** [comment]
i added the filler field with pic X(3) but still it is just displaying one row and in the filler column it is displaying the first 3 characters of next field .

**Comment by tejasbharambe** [comment]
i guess we need to append the binary data to the EBCDIC file as well

**Comment by tejasbharambe** [comment]
i tried appending the binary data to the binary file .
i also edited the copybook accordingly .

it is successfully converting the first row correctly, but it is not displaying all the rows . what might be the issue?

**Comment by tejasbharambe** [comment]
![screenshot-2](https://cloud.githubusercontent.com/assets/13090104/23092497/43170672-f581-11e6-81a0-107ee3215387.png)
this is the output we are getting. why just one row?

@ankravch could you brief us about how did you create the table.?
what are the steps you followed?

@datawarlock :check this out

**Comment by tejasbharambe** [comment]
issue solved .
Thank you so much @datawarlock @ankravch @rbheemana for everything you did. It was a great help. This world needs more people like you all.

**Comment by rbheemana** [comment]
@tejasbharambe Is there something wrong with code? Is the issue genuine? If yes, How did you resolve it? Please post details.

**Comment by tejasbharambe** [comment]
Done the code is perfectly fine. Not an issue.

**Comment by tejasbharambe** [comment]
Hello ram, I have been trying to decode this code but I have been facing some difficulties. If you don't mind and if u have time could you please explain me the flow of the code in short. Use of each class atleast. Thanks in advance.
