### ISSUE TITLE
Trying to add support for the zoned decimal as well. 

### ISSUE THREAD

**Issue by tejasbharambe** [rbheemana/Cobol-to-Hive#32]
We are trying to add the support for zoned decimal as well. We will share the code after we are done.

**Comment by rbheemana** [comment]
Could you please add more detailed description what you are trying to achieve.

**Comment by hp2017** [comment]
Hi @rbheemana,

Apologies in advance if this is irrelevant or not the right place or way to do this and causes any inconvenience.

I am currently looking for a Java application / library that can convert an EBCDIC formatted file (from Mainframe) into standard ASCII format. I came across this code base [Cobol-to-Hive] and found it really interesting. I was wondering if this application also handles packed / compressed fields (COMP-3) conversion and copybooks?

Awaiting a prompt response.

Thanks in advance.

Kind Regards,
Harish

**Comment by rbheemana** [comment]
Yes it does..

**Comment by hp2017** [comment]
Hi @rbheemana ,

Thanks a lot for the quick response.

Just to clarify, sorry i haven't gone through the entire code yet, is the EBCDIC --> ASCII conversion and handling of COMP-3 format done using Java code?

What I am on the look out is a Java library that will handle EBCDIC to ASCII conversion and handles all formats of EBCDIC including COMP-3 fields and copybooks.

Thanks again.

Regards,
Harish

**Comment by rbheemana** [comment]
It is not a java library, it is Hive serde written in java.

**Comment by hp2017** [comment]
Hi @rbheemana ,

Thanks a lot for the quick responses. Really appreciate it.

Regards,
Harish

**Comment by gmsurendra** [comment]
@rbheemana, this issue can be closed it still shows as open.
