### ISSUE TITLE
large Files 

### ISSUE THREAD

**Issue by Leo273** [rbheemana/Cobol-to-Hive#36]
Hi 

Have you does any performance testing , i read the post on large files and the time seems a bit on the higher side . Could you please let me know if Hive internally uses Map-reduce to process a custom SerDe conversion when a Select query is executed 

Thanks
Lep

**Comment by rbheemana** [comment]
Yes it uses Map-reduce

**Comment by vkravoori** [comment]
if Hive internally uses Map-reduce to process a custom SerDe conversion when a Select query is executed, is there a way to select corresponding input file name while selecting a subset of records?

**Comment by rbheemana** [comment]
use Hive provided column name INPUT__FILE__NAME to filter.
