### ISSUE TITLE
Variable Block Duplicates

### ISSUE THREAD

**Issue by dfntrs** [rbheemana/Cobol-to-Hive#37]
Hello,

We've implemented the cobol to Hive Serde, with some small tweaks we previously found for handling COMP-3 values, but we are now seeing some issues with Serde causing duplicate records.  The duplicate records seem to be coming from the split boundary.  The immediate record after the split seems to be duplicated, but not in all scenarios.  We've had some files, with block size divisible by 4, which seems to be the bytereader's approach that worked, and some also that did not work, ruling our our potential assumption we were having issues with Odd sized files.  I was wondering if anyone had noticed this issue and may have some feedback?

**Comment by rbheemana** [comment]
If possible could you please supply logs so that we can replicate the issue.

**Comment by rbheemana** [comment]
closing this issue as it cannot be replicated.
