### ISSUE TITLE
V9(6) in copybook -- not able to create column

### ISSUE THREAD

**Issue by kranthi1128** [rbheemana/Cobol-to-Hive#39]
I have 1 column in copybook as 
01 DETAILS.
   02 RATE PIC V9(6).

Serde is not able to convert ?? Please help .

**Comment by kranthi1128** [comment]
@rbheemana .

**Comment by datawarlock** [comment]
I don't think PIC V9(6) is a valid datatype.  I think you need PIC S9(6).

V9 is for implied decimals after the S9.

**Comment by kranthi1128** [comment]
Thanks for the response.

Below link show that PIC V9 is valid . Any help ??

http://www.csis.ul.ie/cobol/course/DataDeclaration.htm
Some examples:
01 CustDiscount   PIC V99 VALUE .25.

**Comment by datawarlock** [comment]
That is a two digit number that is only an implied decimal.  What error are
you getting?

**Comment by kranthi1128** [comment]
I'm not getting error. Serde is neglecting/skipping that column. when i checked the cobol hive mapping. Column is not there in hive table

**Comment by datawarlock** [comment]
Try
PIC S9(0) V9(6)

Thanks!
*Patrick J. Watts*
*Director of Cloud Engineering*
*M 630-873-9180*

**Comment by kranthi1128** [comment]
Sure, I was about to try S9(0)V9(6). I ll validate this scenario and let you know.

**Comment by kranthi1128** [comment]
it worked with S9(0)V9(6).

**Comment by kranthi1128** [comment]
@datawarlock @rbheemana 

i have one more issue with reading the data. my mainframe binay file has SPACES in one of the comp-3 field. So input is displayed as INVALID in input. 
after the conversion. when i query that column it is giving me some random values like '12000','0','1.2'. Not sure how to handle this.
copybook has datatype as S9(6)V99 COMP-3 and length is 5. I checked the cobol mapping thats also has length of 5.

**Comment by datawarlock** [comment]
This is an issue that I have faced in the past.  To deal with this you need
to increment S9(6) to S9(7).  When dealing with S9 COMP-3 there are never
truly an even number because you always have the last half byte for the
sign.  A mainframe understands this and can accept a value like S9(6) but
the SerDe needs it to be explicit and should be set to S9(7).

Also - I have had problems in the past using short hand V99 and recommend
to always us the short hand V9(2)

Thanks!
*Patrick J. Watts*
*Director of Cloud Engineering*
*M 630-873-9180*

*www.ClarityInsights.com <http://www.ClarityInsights.com>*

**Comment by kranthi1128** [comment]
with S9(7)V9(2), m getting wrong data. Not able to validate against mainframe file. With S9(6)V99 COMP-3. m able to validate all the fields except which have spaces in mainframe file.
I think S9(6)V99 is working as length it is populating is 5 only. So it is good there.

**Comment by kranthi1128** [comment]
@datawarlock 
It was the problem with file having COMP-3 field value as SPACES. i extracted again with making those fields as zero value. It worked. Testing some more scenarios. Will keep this thread updated.

Thanks for the help.

**Comment by rbheemana** [comment]
Code has been updated to support v9(6) directly. Please check branch
https://github.com/rbheemana/Cobol-to-Hive/tree/Issue39%23V9(6)-in-copybook----not-able-to-create-column

**Comment by rbheemana** [comment]
code merged to main branch. closing the issue.
