### ISSUE TITLE
how to remove header and trailer from binary file.

### ISSUE THREAD

**Issue by kranthi1128** [rbheemana/Cobol-to-Hive#40]
Hi @datawarlock @rbheemana , 

i'm getting header and trailer as well in binary file which is sent by external system. How do i ignore those records while reading the file.

Format:
Header(1 row)
Details(1000000 rows)
Trailer(1 row)

help is highly appreciated.

**Comment by kranthi1128** [comment]
can we set tblproperties

"skip.header.line.count"="1"

in order to skip header in binary file. @datawarlock

**Comment by kranthi1128** [comment]
@datawarlock @rbheemana any help on this.

**Comment by kranthi1128** [comment]
header and trailer has different lengths

**Comment by rbheemana** [comment]
@kranthi1128  Create an table with the header and trailer, use where clause to filter these records.
