### ISSUE TITLE
Execution error HiveException: Duplicate column name

### ISSUE THREAD

**Issue by Anchalsangal** [rbheemana/Cobol-to-Hive#41]
We are executing  your jar and performing below steps but we are getting hive exception as shown below. Can you please suggest some solution to this or why we are getting this error.

STEP 1: Add  the CobolSerde.jar to the Hdfs path

STEP 2: Add the layout to the Hdfs path.

STEP 3: Login to Hive

STEP 4: Add the jar.
add jar hdfs://devmid:8020/dev/test/CobolSerde.jar

STEP 5: Run the DDL.

DROP TABLE IF EXISTS abc_enc.cobol_layout2;
CREATE TABLE abc_enc.cobol_layout1
ROW FORMAT SERDE 'com.savy3.hadoop.hive.serde3.cobol.CobolSerDe'
STORED AS
INPUTFORMAT 'org.apache.hadoop.mapred.FixedLengthInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
TBLPROPERTIES ('cobol.layout.url'='hdfs://devmid:8020/dev/test/layout2.txt','fb.length'='1000');

ERROR :
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. org.apache.hadoop.hive.ql.metadata.HiveException: Duplicate column name srvc_fr_dt_ccyy in the table definition.

As per my understanging:
Error point to the layout portion 
            20  SRVC-FROM-DATE.
                           25  SRVC-FR-DT-CCYY  PIC X(4).
                           25  SRVC-FR-DT-MMDD  PIC X(4).
                       20  SRVC-TO-DATE.
                           25  SRVC-TO-DT-CCYY  PIC X(4).
                           25  SRVC-TO-DT-MMDD  PIC X(4).

**Comment by rbheemana** [comment]
please share the entire copybook layout. Looks like there are two fields with that name in copybook.
  
  
  

  
  

  
  
>

**Comment by Anchalsangal** [comment]
Please find attached copybook layout file that we are using.


[layout.txt](https://github.com/rbheemana/Cobol-to-Hive/files/1287687/layout.txt)

**Comment by Anchalsangal** [comment]
Hi rbheemana please find my attached layout file above and please suggest some solution to the problem.

**Comment by Anchalsangal** [comment]
There is one more concern i wanted to ask you there is a file name "MainframeConfiguration" file in your code which i am unable to locate in my code . So please tell me why are we using this file and what all things does this file contain and where do we get this file from . This file is in class "FTPtoHDFS" due to this i am getting compilation error too.

**Comment by nayven3** [comment]
Hi Ram,

I am hereby sharing another scenario which ended up with duplicate field name found.

Scenario:
---------
hive> CREATE TABLE MF_array_Scenario_1
    > ROW FORMAT SERDE 'com.savy3.hadoop.hive.serde3.cobol.CobolSerDe'
    > STORED AS
    > INPUTFORMAT 'org.apache.hadoop.mapred.FixedLengthInputFormat'
    > OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
    > TBLPROPERTIES ('cobol.layout.literal'='01  MF-Array-test.   \
    >                10 CLM-ACNT-REL OCCURS 10 TIMES. \
    >                  15 CLM-NUM.               \
    >                     20 CLM-ACNT-NUM     PIC X(09).      \
    >                     20 ID-CD         PIC X(02).');
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. org.apache.hadoop.hive.ql.metadata.HiveException: Duplicate column name clm_acnt_num in the table definition.

Alternative approach to solve:
---------------------------------
Eliminating the column "15 CLM-NUM. " would resulted in successful creating of table. 

However, There may a possibility of referencing eliminated column could cause program logic failure. Could please assist me.   

Thanks in advance.

**Comment by nayven3** [comment]
Hi Anchal,

In your case also, I have tried to eliminate  20th level variable definition and successfully created the table.

Before modification:
-----------------------
               10  OCHT-ACCUR-DTL-LVL.
                   15  OCHT-ACCUR-DET OCCURS 18 TIMES.
                       20  BILLED-AMT     PIC S9(5)V99
                           SIGN IS LEADING, SEPARATE.
                       20  ROC-COD        PIC X(7).
                       20  OD1            PIC X(2).
                       20  OD2            PIC X(2).
                       20  OS             PIC X(2).
                       20  OS-CATEG-CE PIC X(2).
                       20  TOSP           PIC X(3).
                       20  OUNT           PIC 9(3).
                       20  ALIFIER-I      PIC 9(9).
                       20  XT-RUL         PIC X(5).
                       20  SRVC-FROM-DATE.
                           25  SRVC-FR-DT-CCYY  PIC X(4).
                           25  SRVC-FR-DT-MMDD  PIC X(4).
                       20  SRVC-TO-DATE.
                           25  SRVC-TO-DT-CCYY  PIC X(4).
                           25  SRVC-TO-DT-MMDD  PIC X(4).

After modification:
------------------------
               10  OCHT-ACCUR-DTL-LVL.
                   15  OCHT-ACCUR-DET OCCURS 18 TIMES.
                       20  BILLED-AMT     PIC S9(5)V99
                           SIGN IS LEADING, SEPARATE.
                       20  ROC-COD        PIC X(7).
                       20  OD1            PIC X(2).
                       20  OD2            PIC X(2).
                       20  OS             PIC X(2).
                       20  OS-CATEG-CE PIC X(2).
                       20  TOSP           PIC X(3).
                       20  OUNT           PIC 9(3).
                       20  ALIFIER-I      PIC 9(9).
                       20  XT-RUL         PIC X(5).

                           25  SRVC-FR-DT-CCYY  PIC X(4).
                           25  SRVC-FR-DT-MMDD  PIC X(4).
  
                           25  SRVC-TO-DT-CCYY  PIC X(4).
                           25  SRVC-TO-DT-MMDD  PIC X(4).

Thank you,

**Comment by rbheemana** [comment]
working without modification as well. Hence closing the defect.
