### ISSUE TITLE
How to handle multiple 01 level in copybook

### ISSUE THREAD

**Issue by kranthi1128** [rbheemana/Cobol-to-Hive#42]
Hi @rbheemana @datawarlock ,

I have copybook with multiple 01 levels. How do i handle this with this SERDE.

Please let me know.

**Comment by datawarlock** [comment]
Can you attached the copybook?  
Also - Is the file VB or FB?

**Comment by kranthi1128** [comment]
sample is 

01  ADT-SAMPLE-SEG.
        03  ADT-KTN-CD                     PIC X(03).
        03  ADT-KTN-SRVC		           PIC X(16).
        03  ADT-WLLT-ID                    PIC X(3).
        03  FILLER                         PIC X(28).
01  ADT-MOCK-INFO-SEGMENT.
        03  ADT-NIFT-CD                     PIC X(03).
        03  ADT-NIFT-RUN-DT           		PIC X(08).
        03  ADT-NIFT-RUN-TM           		PIC X(08).

**Comment by datawarlock** [comment]
You can define it like this:

01 ADT-SAMPLE.
  02 ADT-SAMPLE-SEG.
    03 ADT-KTN-CD PIC X(03).
    03 ADT-KTN-SRVC	PIC X(16).
    03 ADT-WLLT-ID PIC X(3).
    03 FILLER PIC X(28).
  02 ADT-MOCK-INFO-SEGMENT REDEFINES ADT-SAMPLE-SEG.
    03 ADT-NIFT-CD PIC X(03).
    03 ADT-NIFT-RUN-DT PIC X(08).
    03 ADT-NIFT-RUN-TM PIC X(08).

**Comment by kranthi1128** [comment]
So it should be always one 01 level?

**Comment by datawarlock** [comment]
I have only ever tried one 01 level.  I know the redefine method works.  My files while complex never had more then one 01 level

**Comment by rbheemana** [comment]
Code has been updated to handle multiple 01 levels but every 01 field must not contain PIC clause.
Test cases are added and are working as expected.
