### ISSUE TITLE
ISSUE WITH PICTURE CLAUSE S99V999 COMP-3. 

### ISSUE THREAD

**Issue by Nandakishore43** [rbheemana/Cobol-to-Hive#45]
I see that, it was coded in such a way to handle  S9(02)V9(03)  COMP-3(which is having brackets)

but not raw format  S99V999 COMP3,  

most of the organizations copybook may have raw format fields 

Ex:   09  PROM-FACTOR            PIC S99V999 COMP-3.

**Comment by rbheemana** [comment]
Code has been updated to deal with raw formats. Hence closing the issue.
