### ISSUE TITLE
S99 not interpreted correctly

### ISSUE THREAD

**Issue by ameet123** [rbheemana/Cobol-to-Hive#46]
Hi Guys,

We are having a problem with specific datatype
Here are the symptoms,
original copybook had S99 which was showing a value ==> null
we changed it to S9(2), still showing the same value ==> null
we changed it to, S9(3) COMP-3 ==> 15012
real value is 1

I'd appreciate if you can offer any insights or ideas on how to solve this.

thanks much,

ameet

**Comment by dfntrs** [comment]
Might trying the following help your issue?
src/main/java/com/savy3/hadoop/hive/serde3/cobo/CobolNumberField.java:

	public Object deserialize(byte[] rowBytes) throws CobolSerdeException {
		byte[] temp = transcodeField(super.getBytes(rowBytes));
		String s1 = new String(temp);

		if (this.compType > 0) {
			if (this.compType == 3) {
				s1 = unpackData(super.getBytes(rowBytes), this.decimalLocation);
			}else if(this.compType == 4){
				s1 = getBinary(super.getBytes(rowBytes), this.decimalLocation);
			}
		//} else if (this.decimalLocation > 0) {
		  } else {
 				//Now calling unpackSign on all numeric fields for which compType resolves to 0.
				//
				//The function will check to see if the least significant byte has been overpunched with a sign and
				//return a negative number if a negative sign is found.
				s1 = unpackSign(super.getBytes(rowBytes), this.decimalLocation);
		}



	//Adding unpackSign to handle signed fields (sign overpunched into the least significant byte)
	public String unpackSign(byte[] packedData, int decimalPointLocation) {
		String unpackedData = "";
		final int negativeSign = 13;
		for (int currentByteIndex = 0; currentByteIndex < packedData.length; currentByteIndex++) {

			int firstDigit = ((packedData[currentByteIndex] >> 4) & 0x0f);
			int secondDigit = (packedData[currentByteIndex] & 0x0F);
			//System.out.println("unpack_"+firstDigit+"_"+secondDigit);
			unpackedData += String.valueOf(secondDigit);
			if (currentByteIndex == (packedData.length - 1)) {
				if (firstDigit == negativeSign) {
					unpackedData = "-" + unpackedData;
				}
			}
		}
		if (decimalPointLocation > 0) {
			unpackedData = unpackedData.substring(0,
					(unpackedData.length() - decimalPointLocation))
					+ "."
					+ unpackedData.substring(unpackedData.length()
							- decimalPointLocation);
		}
		return unpackedData;
	}

**Comment by ameet123** [comment]
ok, so what happens to the 
```
else if (this.decimalLocation > 0) 
```
block? Are you removing it completely? 
Also does the `try/catch` after the `if then else` stay as it is?

sorry*

ah I see that you have added it in the `unpackSign` method

ok let me try to build and give it a shot.

thanks much.

**Comment by rbheemana** [comment]
@dfntrs Thanks for the contribution. I have added the your code to the branch https://github.com/rbheemana/Cobol-to-Hive/tree/Issue%2351-Field-with-format-S9(11)V99-displays-null-value-in-hive

@dfntrs  @ameet123 Could you please test if all scenarios are working fine with the new branch jar

**Comment by rbheemana** [comment]
closing the issue
