### ISSUE TITLE
Db2 to Hive - handling Comp and comp3 data , which are part of a group variable

### ISSUE THREAD

**Issue by VijethaSenigaram** [rbheemana/Cobol-to-Hive#48]
I am currently working on a Mainframes-Db2 to Hadoop , data download.  Facing issues in how to read the data from Hadoop , that is a Mainframes group variable with COMP  and COMP-3 fields 

Below are the details of the Issue. Any suggestions /thoughts/ Information is greatly appreciated. Thankyou in advance !

Example:
columnA of the DB2 table  is equivalent to a group variable in Cobol that is a combination of COMP and COMP-3 variables in Mainframes as shown below

10 COLUMNA                                       
15  AAAA-DAILY-COUNTS OCCURS 30 TIMES.                
    20  AAAA-BBB-REQT-D  PIC S9(05) COMP-3
    20  AAAA-BBBBB-D      PIC S9(09) COMP. 
    
15  AAAA-WEEKLY-COUNTS OCCURS 26 TIMES.                
    20  AAAA-DDDD-W              PIC S9(05) COMP-3.
    20  AAAA-CCCC-IN-VSN-W    PIC S9(09) COMP. 

Data is landed from DB2 to Hadoop using Attunity tool .As part of validation for data landing, we are checking the HEX(ColumnA data in DB2) should be equal to HEX( COLUMN A data in HAdoop).

In what possible ways can we convert 
	1) the HEX form of the compressed field in Hadoop(  which is a Group variable in cobol with comp and comp-3 fields) ,to readable , uncompressed form ?
	2) Or any suggestion on other possible ways

**Comment by rbheemana** [comment]
Not an issue
