### ISSUE TITLE
Issue with parsing the COM-3 columns

### ISSUE THREAD

**Issue by yjaipalreddy** [rbheemana/Cobol-to-Hive#5]
Hi Bheemana,

I have used the serde provided by you to pull the file from mainframe server and was able to create jar file. Created hive table using the serde. when I selected data from hive table.. com-3 fields were not shown correctly.
Mainframe --   hive table output
0                --12000000
0                --12000000
28.66         --12000000.02816
9.66           --12000000.00966

Do you have any idea why it is not able parse com-3 fields

Thanks in advance

**Comment by rbheemana** [comment]
I know that issue, I forgot to update the code on github , could you please try now.
Thanks,Ram

**Comment by rbheemana** [comment]
Updated please try now..

Sent from Outlook on iOS




On Wed, Apr 13, 2016 at 1:18 PM -0700, "yjaipalreddy" <notifications@github.com> wrote:












Hi Bheemana,



I have used the serde provided by you to pull the file from mainframe server and was able to create jar file. Created hive table using the serde. when I selected data from hive table.. com-3 fields were not shown correctly.

Mainframe --   hive table output

0                --12000000

0                --12000000

28.66         --12000000.02816

9.66           --12000000.00966



Do you have any idea why it is not able parse com-3 fields



Thanks in advance

**Comment by yjaipalreddy** [comment]
Hi Ram,

I was not able to get the link for updated code..Could you please post the link to updated code.

I downloaded the zip file but when i compared old code with updated code, i didn't see any changes.

Thanks in advance

Regards
Jaipal Reddy yasa

**Comment by yjaipalreddy** [comment]
Hi Ram,
Could you please check and provide the updated code link..
Thanks!!

**Comment by rbheemana** [comment]
Please share me your copy book, sample input file and ddl statement.

**Comment by yjaipalreddy** [comment]
Hi Ram,

I will not be able to share those for compliance reasons :-).

Is this the file/code you updated to fix the issue(Update CobolSerdeUtils.java )..

I could see the comment but looks like the file is not updated..

if you can provided the update code, we will recreate the jar file and try 

Thanks!!

**Comment by rbheemana** [comment]
I actually did update it. Please try rebuilding jar file or please take the jar file updated under gh pages trunk in target folder.
Please check your is correctly defined, sometimes it might cause the issue.

**Comment by yjaipalreddy** [comment]
Hi Ram,

Sorry to bother you.. I have checked in both master trunk and gh-pages trunk . I found the jar was updated 6 months back and CobolSerdeUtils.java  also updated 6 months ago..

we created jar files again with the code available on github but not much luck there..

If you please don't mine.. could you please check and let me know whether the code was updated and if yes..please provide the link.

![capture](https://cloud.githubusercontent.com/assets/18450104/14617981/6f9f7920-057e-11e6-857f-5a95c85acb78.PNG)
![capture-1](https://cloud.githubusercontent.com/assets/18450104/14617982/6f9f8514-057e-11e6-9cc2-5a66d90bc180.PNG)

**Comment by rbheemana** [comment]
I think the code is already updated, use the jar file and try.

0 --12000000
0 --12000000
28.**66** --12000000.028**16**
9.66 --12000000.00966

Above looks like copybook issue. Please create a small file on mainframe and test it.

Although 3rd example looks little weird

**Comment by rbheemana** [comment]
I have updated the code. Please use com.savy3.hadoop.hive.serde3.cobol.SerDe and verify.
Jar is located @ https://github.com/rbheemana/Cobol-to-Hive/tree/gh-pages/target
