### ISSUE TITLE
 Field with format  S9(11)V99 displays null value in hive.

### ISSUE THREAD

**Issue by danrosenfe** [rbheemana/Cobol-to-Hive#51]
Field with S9 format (11) V99 displays null value in hive.

Please, could you help us to verify if it is a problem or some step was executed incorrectly?

Details are on this drive:  https://drive.google.com/open?id=1DE9nMV055NR1hG0kJIrx74E2nnT9fIW1PS9209A3QSo

regards Daniel

**Comment by rbheemana** [comment]
Could you please provide me the input file.

**Comment by rbheemana** [comment]
https://github.com/rbheemana/Cobol-to-Hive/tree/Issue%2351-Field-with-format-S9(11)V99-displays-null-value-in-hive

@danrosenfe Could you please test if all scenarios are working fine with the above branch jar

**Comment by rbheemana** [comment]
closing the issue

**Comment by danrosenfe** [comment]
Thank you very much for the return at the moment I am on vacation please leave the topic open I will make the tests and send the codes and sample files next week!

**Comment by danrosenfe** [comment]
Hello!

Below link folder on google drive with file and book.

https://drive.google.com/open?id=1z7EcJk-HOp7_qlTFBL5FmgQO3F-06FHZ 

I could not download .jar, could you please provide the link again?

Thank you!

**Comment by rbheemana** [comment]
Code is working fine added the test data provided and tested. Below are results.

Printing results
|issue39_arq.nome|Luis      |#|issue39_arq.sobrenome|Lucci      |#|issue39_arq.idade|23|#|issue39_arq.saldo|520.12|#|issue39_arq.saldo_comp|520.12|
|issue39_arq.nome|Rogerio   |#|issue39_arq.sobrenome|Cardoso    |#|issue39_arq.idade|21|#|issue39_arq.saldo|-44.5|#|issue39_arq.saldo_comp|-44.5|


To build the jar, download the repo and do a maven install. It will create jar and execute the unit test cases.

Try "Intellij" IDE, if you want do via IDE.

**Comment by danrosenfe** [comment]
Hi,
thank you very much with this last jar worked perfect!

Note: in order to compile I needed to delete the test contained in the TestCobolHiveTableCreation.java that generated error.

I am willing to create cobol test files in any format if need be.

Thank you!
