### ISSUE TITLE
How to handle the COBOL EBCDIC file with header of 115 bytes.

### ISSUE THREAD

**Issue by harshitgoyal** [rbheemana/Cobol-to-Hive#64]
Hi Ram,

I have the EBSDIC fie with header of 115 bytes long the actual data starts fro 116.

Record format . . . : VB        
Record length . . . : 521       
Block size  . . . . : 27998     

Please help to for the example layout for such header file.

Regards,
Harshit

**Comment by rbheemana** [comment]
@harshitgoyal use same the copy book that you are using in the mainframe
