### ISSUE TITLE
issues while using cobol serde

### ISSUE THREAD

**Issue by kamelia78** [rbheemana/Cobol-to-Hive#9]
Hello!

Thank you for this great work.
I'm testing the conversion of an EBCDIC File to Hive Table and have some issues:

When using in Hive:
ROW FORMAT SERDE 'com.savy3.hadoop.hive.serde3.cobol.CobolSerDe'
I have the following error:
Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. org.apache.hadoop.hive.ql.metadata.HiveException: at least one column must be specified for the table

HOWEVER,
when using:
ROW FORMAT SERDE 'com.savy3.hadoop.hive.serde2.cobol.CobolSerDe'
It works, but the format  PIC S9(8)V9(3) USAGE COMP-3. is not correct for decimals:
8 instead  of 8.1
9.16 instead of 9.216

Could you please help ?
Thanks!

**Comment by rbheemana** [comment]
share the complete DDL... using serde3..

**Comment by rbheemana** [comment]
Closing the issue because of insufficient data to support the issue.

**Comment by kamelia78** [comment]
ADD JAR hdfs://cluster/user/username/cobolserde.jar;
CREATE EXTERNAL TABLE IF NOT EXISTS new_table
ROW FORMAT SERDE 'com.savy3.hadoop.hive.serde3.cobol.CobolSerDe'
STORED AS
INPUTFORMAT 'org.apache.hadoop.mapred.FixedLengthInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
LOCATION '/TMP/DATA'
TBLPROPERTIES ('cobol.layout.url'= 'hdfs://cluster/user/username/my_layouts/layout','fb.length'='120')

**Comment by kamelia78** [comment]
Hello,
below the DLL

ADD JAR hdfs://cluster/user/username/cobolserde.jar;
CREATE EXTERNAL TABLE IF NOT EXISTS new_table
ROW FORMAT SERDE 'com.savy3.hadoop.hive.serde3.cobol.CobolSerDe'
STORED AS
INPUTFORMAT 'org.apache.hadoop.mapred.FixedLengthInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
LOCATION '/TMP/DATA'
TBLPROPERTIES ('cobol.layout.url'= 'hdfs://cluster/user/username/my_layouts/layout','fb.length'='120')
